### ISSUE TITLE
OPA_CS undefined

### ISSUE THREAD

**Issue by pdelges** [Marzac/OPA-Library#1]
Hello,

OPA_CS n'est pas défini ds l'EditorBrige.ino.
N'est-il de toute façon pas plus prudent d'inclure OPA.h et d'utiliser les OPA_*_PIN qui y sont définis plutôt que de redéfinir toutes les pins?

p

**Comment by farvardin** [comment]
The sketch folder, containing "EditorBridge.ino" on github is not up to date. To get the correct version of the EditorBridge, it is located in the OpaEditor provided for windows, in the editorbridge folder.

Here it is (for linux users):

/*
- OPA Shield
- fredslab.net
- Editor bridge sketch
- 30/06/2016
  */

/*\* OPA shield pin mapping */
#define OPA_TX     0
#define OPA_RX     1
#define OPA_CS1    2
#define OPA_CS2    3
#define OPA_SWAP   4
#define OPA_RESET  7

/*\* Hardware setup */
void setup()
{
    pinMode(OPA_TX, INPUT);
    pinMode(OPA_RX, INPUT);
    pinMode(OPA_CS1, OUTPUT);
    pinMode(OPA_CS2, OUTPUT);
    pinMode(OPA_SWAP, OUTPUT);
    pinMode(OPA_RESET, OUTPUT);

```
digitalWrite(OPA_CS1, 0);
digitalWrite(OPA_CS2, 0);
digitalWrite(OPA_SWAP, 1);
digitalWrite(OPA_RESET, 0);
```

}

/*\* Main program */
void loop()
{
// Do nothing
}

**Comment by Marzac** [comment]
Salut farvardin,
j'ai intégré la nouvelle version du bridge via ta pull request.
Merci, Frédéric
